name: Desplegar a Netlify

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que prefieras desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Especifica la versión de Node.js que necesitas

      - name: Install dependencies
        run: npm install

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy --prod --dir=dist  # Cambia 'dist' al directorio de construcción de tu proyecto
